# Generated by Django 4.2.6 on 2023-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='sub_title',
            field=models.CharField(default=0, max_length=100, verbose_name='اختصار عنوان'),
            preserve_default=False,
        ),
    ]
