# Generated by Django 4.2.6 on 2023-10-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'مقاله و پست', 'verbose_name_plural': 'مقالات و پست ها'},
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='status_choose',
            field=models.CharField(choices=[('pb', 'انتشار یافته'), ('rj', 'رد شده')], default='pb', max_length=2, verbose_name='انتخاب وضعیت'),
        ),
        migrations.AddIndex(
            model_name='postmodel',
            index=models.Index(fields=['-created_at'], name='post_created_f85ddb_idx'),
        ),
    ]
