# Generated by Django 4.2.6 on 2023-10-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_categorymodel_title_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(help_text='write any thing'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
