# Generated by Django 4.2.6 on 2023-10-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_post_body_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',), 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
