# Generated by Django 4.2.6 on 2023-10-16 15:15

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated post'),
        ),
    ]
