# Generated by Django 4.2.6 on 2023-10-17 05:24

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_categorymodel_title_choose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('created_at',), 'verbose_name': 'مقاله و پست', 'verbose_name_plural': 'مقالات و پست ها'},
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='create_category',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد شده دسته بندی'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='posts.categorymodel'),
        ),
    ]
