# Generated by Django 4.2.6 on 2023-10-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/post%Y/%M/%D', verbose_name='عکس')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ManyToManyField(related_name='images', to='posts.imagemodel'),
        ),
    ]
