# Generated by Django 4.2.6 on 2023-10-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_imagemodel_remove_postmodel_image_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='images', to='posts.imagemodel'),
        ),
    ]
