# Generated by Django 4.2.6 on 2023-10-17 05:51

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='create_category',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایحاد یک دسته بندی'),
        ),
    ]
