# Generated by Django 4.2.6 on 2023-10-17 06:54

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_categorymodel_create_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='status_choose',
            field=models.CharField(choices=[('published', 'انتشار یافته'), ('reject', 'رد شده')], default='published', max_length=10, verbose_name='انتخاب وضعیت'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='create_category',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده دسته بندی'),
        ),
    ]
