# Generated by Django 4.2.6 on 2023-10-16 15:13

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلانات'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
