# Generated by Django 4.2.6 on 2023-10-17 13:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_choose', models.CharField(blank=True, choices=[('texhnology', 'تکنولوژی'), ('lifestyle', 'سبک زندگی')], default='----', max_length=10, null=True, verbose_name='انتخاب نوع دسته بندی')),
                ('create_category', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده دسته بندی')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='انتخاب دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'db_table': 'category',
            },
        ),
    ]
