# Generated by Django 4.2.6 on 2023-10-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category',
            field=models.ManyToManyField(related_name='sub_category', to='categories.categorymodel'),
        ),
    ]
