# Generated by Django 4.2.6 on 2023-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title_choose',
            field=models.CharField(choices=[('programming', 'برنامه نویسی'), ('Artificial Intelligence', 'هوش مصنوعی'), ('Electronics', 'لوازم الترونیکی'), ('internet', 'اینترنت'), ('security nad network', 'امنیت و شبکه'), ('computer and hardware', 'کامپویتر و سخت افزار'), ('software and application', 'نرم افزار و اپلیکیشن')], max_length=24, verbose_name='انتخاب نوع دسته بندی'),
        ),
    ]
