# Generated by Django 4.2.6 on 2023-10-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='انتخاب دسته بندی'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='status_category',
            field=models.CharField(blank=True, choices=[('pb', 'انتشار یافته'), ('rj', 'رد شده')], max_length=2, null=True, verbose_name='وضعیت انشتار'),
        ),
    ]
