# Generated by Django 4.2.6 on 2023-10-19 07:21

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategorymodel_alter_categorymodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'verbose_name': 'زیر منو', 'verbose_name_plural': 'زیر منوها'},
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='choose_sub_category',
            field=models.CharField(choices=[('pb', 'published'), ('rj', 'reject')], default=0, max_length=2, verbose_name='وضعیت انتشار زیر منو'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='created_sub_category',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد زیر منو'),
            preserve_default=False,
        ),
    ]
