# Generated by Django 4.2.6 on 2023-10-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categorymodel_title_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='ctegory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categpries', to='categories.categorymodel'),
        ),
    ]
