# Generated by Django 4.2.6 on 2023-10-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_subcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_categorys', to='categories.subcategorymodel'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='choose_sub_category',
            field=models.CharField(choices=[('pb', 'انتشار یافته'), ('rj', 'رد شده')], max_length=2, verbose_name='وضعیت انتشار زیر منو'),
        ),
    ]
