# Generated by Django 4.2.6 on 2023-10-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categorymodel_ctegory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='ctegory',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.categorymodel', verbose_name='Parent Category'),
        ),
    ]
