# Generated by Django 4.2.6 on 2023-10-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_categorymodel_ctegory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(default=0, max_length=100, verbose_name='انتخاب دسته بندی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title_choose',
            field=models.CharField(choices=[('programming', 'برنامه نویسی'), ('Artificial Intelligence', 'هوش مصنوعی'), ('Electronics', 'لوازم الترونیکی'), ('internet', 'اینترنت'), ('security nad network', 'امنیت و شبکه'), ('computer and hardware', 'کامپیوتر و سخت افزار'), ('software and application', 'نرم افزار و اپلیکیشن')], max_length=24, verbose_name='انتخاب عنوان دسته بندی'),
        ),
    ]
