# Generated by Django 4.2.6 on 2023-10-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='sub_categorys', to='categories.subcategorymodel'),
        ),
    ]
