# Generated by Django 4.2.6 on 2023-10-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_remove_categorymodel_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='title_choose',
            field=models.CharField(choices=[('برنامه نویسی', 'Programming'), ('هوش مصنوعی', 'Artificial Intelligence'), ('لوازم الترونیکی', 'Electronics'), ('اینترنت', 'Internet'), ('امنیت و شبکه', 'Security And Network'), ('کامپیوتر و سخت افزار', 'Computer And Hardware'), ('نرم افزار و اپلیکیشن', 'Software And Application')], default=None, max_length=24, verbose_name='انتخاب عنوان دسته بندی'),
        ),
    ]
