# Generated by Django 4.2.6 on 2023-10-19 09:10

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMoel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('created_at_ticket', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد تیکت')),
                ('body', models.TextField(verbose_name='متن تیکت')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'db_table': 'ticket',
            },
        ),
    ]
